// <auto-generated />
namespace AphidBT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration03aug2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration03aug2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202008032156038_migration-03aug2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
